ARG BASE

FROM $BASE

ARG AUTHOR
ARG VERSION
LABEL maintainer=${AUTHOR} version=${VERSION}

ARG TARGETOS
ARG TARGETARCH

# Update Ubuntu
ENV DEBIAN_FRONTEND=noninteractive
ENV VPYTHON_BYPASS="manually managed python not supported by chrome operations"

COPY .beagle/build.sh /tmp/build.sh
RUN chmod +x /tmp/build.sh && \
/tmp/build.sh