ARG BASE

FROM $BASE

ARG AUTHOR
ARG VERSION
LABEL maintainer=${AUTHOR} version=${VERSION}

ARG TARGETOS
ARG TARGETARCH

# Update Ubuntu
ENV DEBIAN_FRONTEND=noninteractive
ENV VPYTHON_BYPASS="manually managed python not supported by chrome operations"
RUN echo Cache V3
RUN apt-get update
RUN apt-get install --upgrade -qq -y --no-install-recommends git curl wget build-essential software-properties-common patchelf maven sudo zip unzip execstack cmake
RUN apt-get install --upgrade -qq -y --no-install-recommends python3 python python3-pip python3-distutils python3-testresources ninja
RUN apt-get upgrade -y
RUN pip3 install coloredlogs